//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace May15ORM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobs
    {
        public string code { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public string joblocation { get; set; }
        public Nullable<int> minsalary { get; set; }
        public Nullable<int> maxsalary { get; set; }
        public System.Guid id { get; set; }
    }
}
